# Generated by Django 5.2 on 2025-05-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
